[package]
name = "implant"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4.3"
hmac = "0.12.1"
rand = "0.9.2"
serde = { version = "1.0", features = ["derive"] }

serde_json = "1.0"
sha2 = "0.10.9"
